PR: Execerise 2 (WIP)
Systems-Development-and-Frameworks/CountryRoads pull request #3
Opened 2020-10-31 10:55 UTC by ilonae

2020-11-04 20:12 UTC, MaykAkifovski commented on exercises/webapp/.storybook/webpack.config.js
> +      ]*/
It's a good practice not to commit a commented code. Once commented it's already altered and is seen as a code smell.

2020-11-04 20:51 UTC, MaykAkifovski requested changes

2020-11-04 20:51 UTC, MaykAkifovski commented on exercises/webapp/src/components/ListNews/ListNews.spec.js
> +    wrapper.vm.update({ id: 2, title: "Rocks", votes: -5 });
You are testing multiple elements of your component in this test. Isn't it better to initialise the ListNews Component with some News with different votes and then to check the sorting.

2020-11-04 20:51 UTC, MaykAkifovski commented on exercises/webapp/src/components/ListNews/ListNews.spec.js
> +          descending: true,
Here you define descending as property and in the program it is defined as asc.

2020-11-04 20:51 UTC, MaykAkifovski commented on exercises/webapp/src/components/ListNews/ListNews.vue
> +      asc: 1,
See comentar in Test.

2020-11-04 20:51 UTC, MaykAkifovski commented on exercises/webapp/src/components/ListNews/ListNews.vue
> +      let newList = [...this.newsList];
Is it needed to copy the list?

2020-11-04 20:51 UTC, MaykAkifovski commented on exercises/webapp/src/components/News/News.spec.js
> +  it("Test coverage for delete emit", async () => {
Please provide a better test description!

2020-11-04 20:51 UTC, MaykAkifovski commented on exercises/webapp/src/components/News/News.spec.js
> +    wrapper.vm.updateItem(5);
Is it possible to upvote a news by 5?

2020-11-04 20:51 UTC, MaykAkifovski commented on exercises/webapp/src/components/News/News.vue
> +      default: () => ({}),
Is it possible to have an empty news?

2020-11-09 10:25 UTC, SarahLM approved these changes
_Well done!_

2020-11-09 10:25 UTC, SarahLM commented on .github/workflows/ci_lint_test.yml
> +        run: yarn test:unit
You could run lint and jest in two different jobs, then the evaluation would be clearer. Otherwise great!

2020-11-09 10:25 UTC, SarahLM commented on exercises/webapp/src/components/ListNews/ListNews.vue
> +          v-bind:news="item"
you could also write  "v-bind: news =" item "" without "v-bind" in front of it and only use the shortcut ": news =" item ""

2020-11-10 21:51 UTC, MaykAkifovski approved these changes
now it lgtm

2020-11-14 13:30 UTC, medizinmensch approved these changes
You got points...

* :star:   for adding the linter, lint fails in case of errors
* :star:   for creating a story for all of your components, locating them correcctly and   adding the @storybook/addon-essentials along with @storybook/addon-a11y
* :star:   for setting up your component properties in real time
* :star:   for passing all acccessibility tests
* :star:   for requesting PR review as well as reviewing anothers teams code

So you've got 10/10 ⭐ ! 

But let me emphasize on one suggestion from my side:
For moving files from one place to another: please do NOT use your file manager (finder/explorer/VS Code). Please use git instead. Because for git it looks like deleting and creating them somewhere else. Then we have many deleted and newly created files. This results in a messy and enormous PR. You also destroy file history like that (e.g. can't use git blame anymore to properly find out who wrote what). Move them either with a git gui or `git mv ./src ./dest`.
More info here:
https://koukia.ca/rename-or-move-files-in-git-e7259bf5a0b7

Apart from that, great job!

![Good job](https://media.giphy.com/media/3o7abGQa0aRJUurpII/giphy.gif)

2020-11-14 13:30 UTC, medizinmensch commented on .github/workflows/ci_lint_test.yml
> +        run: yarn test:unit
I agree with @SarahLM here. 
But your implementation gets the job done. 

So :star:   for setting up a build server that tests and lints your code

2020-11-14 13:30 UTC, medizinmensch commented on exercises/webapp/src/components/CreatNews/CreateNews.spec.js
> +describe("CreateNews", () => {
:star:   for testing your components with jest and vue-test-utils

2020-11-14 13:30 UTC, medizinmensch commented on exercises/webapp/src/components/ListNews/ListNews.spec.js
> +  describe('given empty list', () => {
:star:   for the empty-list-feature and it's test

2020-11-14 13:30 UTC, medizinmensch commented on exercises/webapp/src/components/ListNews/ListNews.spec.js
> +  it("should check functionality of sorting button", async () => {
:star:   for the toggle between ascending and desccending order and it's test

I would change the title here (and with the other tests) to something like "should toggle between ascending / descending" and thus leaving out "functionality" and "check"

2020-11-14 13:30 UTC, medizinmensch commented on exercises/webapp/package.json
> +  "jest": {
:star:   for configuring jest in a way so you can locate component, story and spec in   one folder

2020-11-16 21:59 UTC, merged